### ISSUE TITLE
Alternative easy & secure way to verify the integrity

### ISSUE THREAD

**Issue by rugk** [PrivateBin/WebExtension#14]
Another way to verify the integrity would be to calculate a SHA-256 hash of the returned index file and compare it with a hash list of valid index files (for al templates). This way the other hashes do not need to be verified and we even make sure that the HTML template code has not been modified (which is bad for customization, of course).

What's your opinion on this method?

**Comment by elrido** [comment]
First the template is one of the things many installs modify. Second, the index files hash changes all the time due to the included encrypted message and the various translations.

**Comment by gjedeer** [comment]
Does the template matter? It's only presentation, if it can't add scripts it can't be malicious, can it?

**Comment by rugk** [comment]
> It's only presentation, if it can't add scripts it can't be malicious, can it?

As far as I know, it can't. So from a security perspective it can be modified.
It is just easier to implement the verification of one hash than to verify the content.

But as I see this idea is bad as many people modify the template and we already have another basic implementation, so I am closing this.
