### ISSUE TITLE
Use real JSDOC

### ISSUE THREAD

**Issue by rugk** [PrivateBin/WebExtension#4]
We should use real [jsdoc](http://usejsdoc.org/) e.g. [here](https://github.com/PrivateBin/WebExtension/blob/master/content-script.js#L18-L26)

**Comment by rugk** [comment]
Fixed by https://github.com/PrivateBin/WebExtension/commit/15374778902b7c2bc358379f88ce1f039fc5e861

@gjedeer I cleaned this code up a bit using the Revealing Module Pattern. Additionally I needed to intend many lines correctly, so please pay attention to correctly intend if blocks and so on…
Also 4 spaces indentation (consider using [editorconfig](https://github.com/PrivateBin/WebExtension/blob/master/.editorconfig#L14)).

I have not tested the code there yet.

**Comment by gjedeer** [comment]
Any standard i should adhere to? The indentation was ok in my vim but i can configure it to your standards.

On December 14, 2016 12:26:46 AM CET, rugk <notifications@github.com> wrote:
>Closed #4.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/PrivateBin/WebExtension/issues/4#event-892864242

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rugk** [comment]
http://editorconfig.org/

Apart from that I'd suggest just to choose the same style as I used in the JS file. (a type of the Revealing Module Pattern, which I think is very clean, tidy and easy to understand)
